services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - monitoringnet
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana:/etc/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoringnet
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}

networks:
  monitoringnet:
    driver: bridge
    
volumes:
  prometheus_data:
  grafana_data:
