blank_issues_enabled: false
template-chooser:
  - name: Bug Report
    about: File a bug report
    template: bug_report.md
  - name: Feature Request
    about: Suggest an idea for this project
    template: feature_request.md
  - name: Generic Issue
    about: Make a general issue
    template: generic_issue.md