name: Deploy to docker hub

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Build images and push to docker hub
      - name: Build and push dbimage
        uses: docker/build-push-action@v6
        with:
          context: ./db
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dbimage:${{ github.ref_name }}

      - name: Build and push backendimage
        uses: docker/build-push-action@v6
        with:
          context: ./backend/API
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backendimage:latest

      - name: Build and push frontendimage
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontendimage:latest

      - name: Build and push proxyimage
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/proxyimage:latest
