name: Deployment

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Build images and push to docker hub
      - name: Build and push dbimage
        uses: docker/build-push-action@v6
        with:
          context: ./db
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/dbimage:latest
            ${{ secrets.DOCKER_USERNAME }}/dbimage:${{ github.ref_name }}

      - name: Build and push backendimage
        uses: docker/build-push-action@v6
        with:
          context: ./backend/API
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/backendimage:latest
            ${{ secrets.DOCKER_USERNAME }}/backendimage:${{ github.ref_name }}

      - name: Build and push frontendimage
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/frontendimage:latest
            ${{ secrets.DOCKER_USERNAME }}/frontendimage:${{ github.ref_name }}

      - name: Build and push proxyimage
        uses: docker/build-push-action@v6
        with:
          context: ./nginx
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/proxyimage:latest
            ${{ secrets.DOCKER_USERNAME }}/proxyimage:${{ github.ref_name }}

  deploy-app-to-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server1
        uses: appleboy/ssh-action@v1.0.3
        with:
          ## TODO: Add your server IP, username and private key
          host: ${{ secrets.VM_IP_1 }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ./app
            echo "Pulling latest images from Docker Hub"
            docker compose pull
            echo "Updating containers and removing old ones"
            docker compose up -d --remove-orphans
            echo "Cleaning up unused containers and resources"
            docker system prune -f

  deploy-db-to-production:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to server2
        uses: appleboy/ssh-action@v1.0.3
        with:
          ## TODO: Add your server IP, username and private key
          host: ${{ secrets.VM_IP_2 }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ./app
            echo "Pulling latest images from Docker Hub"
            docker compose pull
            echo "Updating containers and removing old ones"
            docker compose up -d --remove-orphans
            echo "Cleaning up unused containers and resources"
            docker system prune -f
