name: Deploy Monitoring Stack

# Triggers on push to main branch that contains changes to monitoring files OR on manual trigger
on:
  pull_request:
    paths:
      - 'monitoring/**'
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Creates directories on the VM if they don't exist
      - name: Create monitoring directories
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MONITORING_VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.MONITORING_VM_SSH_KEY }}
          script: |
            mkdir -p ~/monitoring
        # Copies monitoring files to the VM
      - name: Copy monitoring files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MONITORING_VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.MONITORING_VM_SSH_KEY }}
          source: "monitoring/*"
          target: "~/monitoring"
          strip_components: 1
        # Deploys the monitoring stack
      - name: Deploy monitoring stack
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.MONITORING_VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.MONITORING_VM_SSH_KEY }}
          envs: |
            GRAFANA_ADMIN_USER,
            GRAFANA_ADMIN_PASSWORD,
            VM_IP_1
          script: |
            cd ~/monitoring
            echo "GRAFANA_ADMIN_USER=${{ secrets.GRAFANA_ADMIN_USER }}" > .env
            echo "GRAFANA_ADMIN_PASSWORD=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" >> .env
            echo "VM_IP_1=${{ secrets.VM_IP_1 }}" >> .env
            export VM_IP_1=${{ secrets.VM_IP_1 }}
            envsubst < prometheus/prometheus.yml.template > prometheus/prometheus.yml
            docker compose pull
            docker compose up -d --remove-orphans
            docker system prune -f